# Generated by Django 5.1.7 on 2025-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContract_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('dob', models.TextField()),
                ('gender', models.TextField()),
                ('identityType', models.TextField()),
                ('identityNumber', models.TextField()),
                ('frontCopy', models.FileField(upload_to='documents/tenant-identity-documents')),
                ('backCopy', models.FileField(upload_to='documents/tenant-identity-documents')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
