from django.urls import path
from . import views

urlpatterns = [
    path('login-data/', views.login_view, name='login-data'),
    path('logout/', views.logout_view, name='logout'),
    path('auth-check/', views.auth_check, name='auth-check'),
    path('get-user-activity-data/', views.get_user_activity_data, name='get_user_activity_data'),
    path('vendor-form-submit/', views.vendor_form_submit, name='vendor_form_submit'),
    path('get-vendor-data/', views.get_vendor_data, name='get_vendor_data'),
    path('vendor-data-update/<str:id>/', views.vendor_data_update, name='vendor_data_update'),
    path('get-property-data/', views.get_property_data, name='get_property_data'),
    path('get-owner-data/', views.get_owner_data, name='get_owner_data'),
    path('get-owner-rooms/<str:id>/', views.get_owner_rooms, name='get_owner_rooms'),
    path('get-resident-data/<str:property_name>/<str:room>/', views.get_resident_data, name='get_resident_data'),
    path('expense-form-submit/', views.expense_form_submit, name='expense_form_submit'),
    path('expense-form-edit/<str:id>/', views.expense_form_edit, name='expense_form_edit'),
    path('get-expense-data/', views.get_expense_data, name='get_expense_data'),
    path('accounts-form-update/<str:id>/', views.accounts_form_update, name='accounts_form_update'),
    path('accounts-form-delete/<str:id>/', views.accounts_form_delete, name='accounts_form_delete'),
    path('fixed-expense-form-submit/', views.fixed_expense_form_submit, name='fixed_expense_form_submit'),
    path('get-fixed-expense-data/', views.get_fixed_expense_data, name='get_fixed_expense_data'),
    path('accounts-fixed-expense-update/<str:id>/', views.accounts_fixed_expense_update, name='accounts_fixed_expense_update'),
    path('accounts-fixed-expense-delete/<str:id>/', views.accounts_fixed_expense_delete, name='accounts_fixed_expense_delete'),
    path('get-beds-data/', views.get_beds_data, name='get_beds_data'),
    path('get-checked-out-residents/', views.get_checked_out_residents, name='get_checked_out_residents'),
    path('liability-form-submit/', views.liability_form_submit, name='liability_form_submit'),
    path('liability-data-update/<str:id>/', views.liability_data_update, name='liability_data_update'),
    path('rawdata-file-upload/', views.rawdata_file_upload, name='rawdata_file_upload'),
    path('get-rawdata-file/', views.get_rawdata_file, name='get_rawdata_file'),
    path('get-rawdata-content/<str:id>/', views.get_rawdata_content, name='get_rawdata_content'),
    path('rawdata-file-delete/<str:id>/', views.rawdata_file_delete, name='rawdata_file_delete'),
    path('rawdata-form-submit/<str:id>/', views.rawdata_form_submit, name='rawdata_form_submit'),
    path('rawdata-form-update/<str:id>/', views.rawdata_form_update, name='rawdata_form_update'),
    path('rawdata-form-delete/<str:id>/', views.rawdata_form_delete, name='rawdata_form_delete'),
    path('other-files-upload/', views.other_files_upload, name='other_files_upload'),
    path('get-other-files/', views.get_other_files, name='get_other_files'),
    path('other-file-delete/<str:id>/', views.other_file_delete, name='other_file_delete'),
    path('get-liability-data/', views.get_liability_data, name='get_liability_data'),
    path('get-dropdown-config/', views.get_dropdown_config, name='get_dropdown_config'),
    path('get-staff-names/', views.get_staff_names, name='get_staff_names'),
    path('employee-form-submit/', views.employee_form_submit, name='employee_form_submit'),
]