# Generated by Django 5.1.7 on 2025-06-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livingRoom', models.ImageField(blank=True, null=True, upload_to='images/property-images/')),
                ('bedRoom', models.ImageField(blank=True, null=True, upload_to='images/property-images/')),
                ('kitchenArea', models.ImageField(blank=True, null=True, upload_to='images/property-images/')),
                ('bathroom', models.ImageField(blank=True, null=True, upload_to='images/property-images/')),
                ('commonArea', models.ImageField(blank=True, null=True, upload_to='images/property-images/')),
                ('productImg', models.ImageField(upload_to='images/property-images/')),
                ('propertyName', models.CharField()),
                ('propertyLocation', models.CharField()),
                ('propertyAddress', models.TextField(blank=True, null=True)),
                ('propertyRoomRent', models.CharField(blank=True, null=True)),
                ('propertyDescription', models.TextField(blank=True, null=True)),
                ('propertyPathname', models.CharField(blank=True, null=True)),
                ('propertyIframeLink', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField()),
                ('ownerPhone', models.CharField()),
                ('ownerEmail', models.CharField()),
                ('ownerAddress', models.CharField()),
                ('ownerDob', models.CharField()),
                ('ownerGender', models.CharField()),
                ('aadharNumber', models.CharField()),
                ('panNumber', models.CharField()),
                ('accountHolderName', models.CharField()),
                ('accountNumber', models.CharField()),
                ('bankName', models.CharField()),
                ('bankBranch', models.CharField()),
                ('ifscCode', models.CharField()),
                ('aadharFrontCopy', models.FileField(upload_to='documents/owner-documents/%Y/%m/%d/')),
                ('aadharBackCopy', models.FileField(upload_to='documents/owner-documents/%Y/%m/%d/')),
                ('panFrontCopy', models.FileField(upload_to='documents/owner-documents/%Y/%m/%d/')),
                ('panBackCopy', models.FileField(upload_to='documents/owner-documents/%Y/%m/%d/')),
                ('chequeCopy', models.FileField(upload_to='documents/owner-documents/%Y/%m/%d/')),
                ('noOfProperties', models.CharField()),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='stayease_su_last_ac_b76eac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Property_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField()),
                ('propertyType', models.CharField()),
                ('doorBuilding', models.CharField()),
                ('streetAddress', models.CharField()),
                ('area', models.CharField()),
                ('landmark', models.CharField(blank=True, null=True)),
                ('state', models.CharField()),
                ('city', models.CharField()),
                ('pincode', models.CharField()),
                ('selectedMealTypes', models.CharField()),
                ('rent', models.CharField()),
                ('deposit', models.CharField()),
                ('rentFree', models.CharField()),
                ('noOfBasements', models.CharField()),
                ('noOfFloors', models.CharField()),
                ('noOfRooms', models.CharField()),
                ('saleDeed', models.FileField(upload_to='documents/property-documents/%Y/%m/%d/')),
                ('ebill', models.FileField(upload_to='documents/property-documents/%Y/%m/%d/')),
                ('taxReceipt', models.FileField(upload_to='documents/property-documents/%Y/%m/%d/')),
                ('waterBill', models.FileField(upload_to='documents/property-documents/%Y/%m/%d/')),
                ('loi', models.FileField(upload_to='documents/property-documents/%Y/%m/%d/')),
                ('agreement', models.FileField(upload_to='documents/property-documents/%Y/%m/%d/')),
                ('status', models.CharField(default='Pending')),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='stayease_supply.owner_data')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Price_Board_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(blank=True, null=True)),
                ('roomRent', models.CharField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceBoardDetails', to='stayease_supply.property_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/neighbourhood-images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoodImages', to='stayease_supply.property_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingLevel', models.CharField()),
                ('roomNo', models.CharField(blank=True, max_length=255, null=True)),
                ('roomType', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending')),
                ('is_basement', models.BooleanField(default=False, editable=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='stayease_supply.property_data')),
            ],
        ),
        migrations.CreateModel(
            name='Bed_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('balconyAccess', models.CharField(blank=True, max_length=255, null=True)),
                ('bathAccess', models.CharField(blank=True, max_length=255, null=True)),
                ('roomType', models.CharField(blank=True, max_length=255, null=True)),
                ('energyPlan', models.CharField(blank=True, max_length=255, null=True)),
                ('hallAccess', models.CharField(blank=True, max_length=255, null=True)),
                ('kitchenAccess', models.CharField(blank=True, max_length=255, null=True)),
                ('roomSqft', models.CharField(blank=True, max_length=255, null=True)),
                ('tataSkyNo', models.CharField(blank=True, max_length=255, null=True)),
                ('wifiNo', models.CharField(blank=True, max_length=255, null=True)),
                ('bescomMeterNo', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='stayease_supply.room_data')),
            ],
        ),
        migrations.AddIndex(
            model_name='property_data',
            index=models.Index(fields=['-last_activity'], name='stayease_su_last_ac_85ddcb_idx'),
        ),
    ]
