# Generated by Django 5.1.7 on 2025-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='noOfBasements',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='noOfFloors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='noOfRooms',
            field=models.IntegerField(),
        ),
    ]
