# Generated by Django 5.1.7 on 2025-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0002_alter_property_data_noofbasements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='noOfBasements',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='noOfFloors',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='noOfRooms',
            field=models.CharField(),
        ),
    ]
