# Generated by Django 5.1.7 on 2025-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0003_alter_property_data_noofbasements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='selectedMealTypes',
            field=models.JSONField(),
        ),
    ]
