# Generated by Django 5.1.7 on 2025-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0004_alter_property_data_selectedmealtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_data',
            name='status',
        ),
    ]
