# Generated by Django 5.1.7 on 2025-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0005_remove_property_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_data',
            name='noOfProperties',
            field=models.IntegerField(),
        ),
    ]
