# Generated by Django 5.1.7 on 2025-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0007_alter_owner_data_noofproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_data',
            name='noOfProperties',
            field=models.IntegerField(),
        ),
    ]
