# Generated by Django 5.1.7 on 2025-06-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0009_bed_data_checkin_bed_data_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='salesStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
