# Generated by Django 5.1.7 on 2025-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0010_bed_data_salesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_data',
            name='foundedYear',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_data',
            name='serial_number',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
