# Generated by Django 5.1.7 on 2025-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0011_property_data_foundedyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_data',
            name='memberSince',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
