# Generated by Django 5.1.7 on 2025-06-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0012_owner_data_membersince'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_data',
            name='aadharVerification',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner_data',
            name='panVerification',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
