# Generated by Django 5.1.7 on 2025-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0013_owner_data_aadharverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_data',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/property-images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property_data',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property_data',
            name='selectedAmenities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property_data',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
