# Generated by Django 5.1.7 on 2025-06-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0014_property_data_image_property_data_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='rating',
            field=models.CharField(blank=True, null=True),
        ),
    ]
