# Generated by Django 5.1.7 on 2025-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0015_alter_property_data_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_data',
            name='aadharVerification',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner_data',
            name='memberSince',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner_data',
            name='panVerification',
            field=models.CharField(blank=True, null=True),
        ),
    ]
