# Generated by Django 5.1.7 on 2025-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0016_alter_owner_data_aadharverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_data',
            name='accountStatus',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner_data',
            name='paymentType',
            field=models.CharField(blank=True, null=True),
        ),
    ]
