# Generated by Django 5.1.7 on 2025-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0017_owner_data_accountstatus_owner_data_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='serial_number',
            field=models.CharField(max_length=20),
        ),
    ]
