# Generated by Django 5.1.7 on 2025-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0018_alter_property_data_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_data',
            name='aadharBackCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='owner_data',
            name='aadharFrontCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='owner_data',
            name='chequeCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='owner_data',
            name='panBackCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='owner_data',
            name='panFrontCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='documents/property-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='ebill',
            field=models.FileField(blank=True, null=True, upload_to='documents/property-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='loi',
            field=models.FileField(blank=True, null=True, upload_to='documents/property-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='saleDeed',
            field=models.FileField(blank=True, null=True, upload_to='documents/property-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='selectedMealTypes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='taxReceipt',
            field=models.FileField(blank=True, null=True, upload_to='documents/property-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property_data',
            name='waterBill',
            field=models.FileField(blank=True, null=True, upload_to='documents/property-documents/%Y/%m/%d/'),
        ),
    ]
