# Generated by Django 5.1.7 on 2025-07-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0019_alter_owner_data_aadharbackcopy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_data',
            name='owner',
        ),
        migrations.AddField(
            model_name='property_data',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to='stayease_supply.owner_data'),
        ),
    ]
