# Generated by Django 5.1.7 on 2025-07-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0021_remove_property_data_owner_property_data_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='stayease_supply.owner_data'),
        ),
    ]
