# Generated by Django 5.1.7 on 2025-07-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0022_alter_property_data_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='stayease_supply.owner_data'),
            preserve_default=False,
        ),
    ]
