# Generated by Django 5.1.7 on 2025-07-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0023_alter_property_data_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='aadharBackCopy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='aadharFrontCopy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='aadharNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='aadharStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='kycType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='panBackCopy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='panFrontCopy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='panNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='panStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
