# Generated by Django 5.1.7 on 2025-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0024_bed_data_aadharbackcopy_bed_data_aadharfrontcopy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed_data',
            name='aadharBackCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bed_data',
            name='aadharFrontCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bed_data',
            name='panBackCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bed_data',
            name='panFrontCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/'),
        ),
    ]
