# Generated by Django 5.1.7 on 2025-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0025_alter_bed_data_aadharbackcopy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='permanentAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
