# Generated by Django 5.1.7 on 2025-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0026_bed_data_permanentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='rentStatus',
            field=models.CharField(default='Not Received'),
        ),
    ]
