# Generated by Django 5.1.7 on 2025-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0027_bed_data_rentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='moveInChecklistStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
