# Generated by Django 5.1.7 on 2025-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0028_bed_data_moveincheckliststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='moveInFeedbackStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
