# Generated by Django 5.1.7 on 2025-07-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0029_bed_data_moveinfeedbackstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='moveOutChecklistStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
