# Generated by Django 5.1.7 on 2025-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0030_bed_data_moveoutcheckliststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='moveOutFeedbackStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
