# Generated by Django 5.1.7 on 2025-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0031_bed_data_moveoutfeedbackstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
