# Generated by Django 5.1.7 on 2025-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0032_bed_data_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed_data',
            name='last_updated',
        ),
    ]
