# Generated by Django 5.1.7 on 2025-07-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0033_remove_bed_data_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
