# Generated by Django 5.1.7 on 2025-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0034_bed_data_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_data',
            name='transferType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='transferredDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bed_data',
            name='utrNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
