# Generated by Django 5.1.4 on 2026-04-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0036_user_activity_data_user_login_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_data',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
