# Generated by Django 5.1.4 on 2026-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_supply', '0038_floor_numbering_zero_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_data',
            name='rentFreeUnit',
            field=models.CharField(blank=True, default='Days', null=True),
        ),
    ]
