# Generated by Django 5.1.7 on 2025-06-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('headOfExpense', models.CharField(max_length=100)),
                ('expenseType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/accounts-other-files/%Y/%m/%d/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='stayease_ac_last_ac_d552b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawdataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawdataFile', models.FileField(upload_to='documents/accounts-files/%Y/%m/%d/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='stayease_ac_last_ac_462826_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rawdata_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('desc', models.CharField()),
                ('type', models.CharField()),
                ('balance', models.CharField()),
                ('debit', models.CharField()),
                ('credit', models.CharField()),
                ('propertyName', models.CharField()),
                ('headOfExpense', models.CharField()),
                ('expenseType', models.CharField()),
                ('category', models.CharField()),
                ('status', models.CharField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='documents/accounts-receipts/%Y/%m/%d/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rawdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawdata', to='stayease_accounts.rawdatafile')),
            ],
            options={
                'verbose_name': 'Raw Data Detail',
                'verbose_name_plural': 'Raw Data Details',
            },
        ),
        migrations.CreateModel(
            name='Vendor_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField()),
                ('contact', models.CharField()),
                ('category', models.CharField()),
                ('billingType', models.CharField()),
                ('accountHolderName', models.CharField(blank=True, null=True)),
                ('accountNumber', models.CharField(blank=True, null=True)),
                ('bankName', models.CharField(blank=True, null=True)),
                ('bankBranch', models.CharField(blank=True, null=True)),
                ('ifscCode', models.CharField(blank=True, null=True)),
                ('upiNumber', models.CharField(blank=True, null=True)),
                ('otherBankingDetails', models.CharField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='stayease_ac_last_ac_a62079_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense_Category_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseRaisedEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('paymentType', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorType', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='documents/accounts-receipts/%Y/%m/%d/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('transferType', models.CharField(blank=True, max_length=100, null=True)),
                ('utrNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expense_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='stayease_accounts.expense_detail')),
                ('vendor_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_categories', to='stayease_accounts.vendor_detail')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
            },
        ),
    ]
