# Generated by Django 5.1.7 on 2025-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_detail',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
