# Generated by Django 5.1.7 on 2025-06-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0002_expense_detail_owner'),
        ('stayease_supply', '0016_alter_owner_data_aadharverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_detail',
            name='owner_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_expenses', to='stayease_supply.owner_data'),
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
