# Generated by Django 5.1.7 on 2025-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0003_expense_detail_owner_instance_expense_detail_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata_detail',
            name='owner',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata_detail',
            name='room',
            field=models.CharField(blank=True, null=True),
        ),
    ]
