# Generated by Django 5.1.7 on 2025-06-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0004_rawdata_detail_owner_rawdata_detail_room'),
        ('stayease_supply', '0016_alter_owner_data_aadharverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata_detail',
            name='owner_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_rawdata', to='stayease_supply.owner_data'),
        ),
    ]
