# Generated by Django 5.1.7 on 2025-07-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0005_rawdata_detail_owner_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_category_detail',
            name='accountId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
