# Generated by Django 5.1.7 on 2025-07-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0006_expense_category_detail_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_category_detail',
            name='dashboardUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
