# Generated by Django 5.1.7 on 2025-07-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0008_remove_expense_category_detail_dashboarduser_and_more'),
        ('stayease_supply', '0023_alter_property_data_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed_Expense_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardUser', models.CharField(max_length=100)),
                ('expenseRaisedEmail', models.CharField(max_length=100)),
                ('propertyName', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('rental', models.CharField(max_length=100)),
                ('tds', models.CharField(max_length=100)),
                ('deductions', models.CharField(max_length=100)),
                ('owner_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_fixed_expenses', to='stayease_supply.owner_data')),
            ],
        ),
    ]
