# Generated by Django 5.1.7 on 2025-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0009_fixed_expense_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
