# Generated by Django 5.1.7 on 2025-07-13 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0010_fixed_expense_detail_comments'),
        ('stayease_supply', '0023_alter_property_data_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixed_expense_detail',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='fixed_expense_detail',
            index=models.Index(fields=['-last_activity'], name='stayease_ac_last_ac_61694d_idx'),
        ),
    ]
