# Generated by Django 5.1.7 on 2025-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0011_alter_fixed_expense_detail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
