# Generated by Django 5.1.7 on 2025-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0012_fixed_expense_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='amountTransferred',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='dateOfTransfer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='transferType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='utrNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
