# Generated by Django 5.1.7 on 2025-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0013_fixed_expense_detail_amounttransferred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='ownerEmail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
