# Generated by Django 5.1.7 on 2025-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0015_fixed_expense_detail_rentalaftertds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='emailNote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
