# Generated by Django 5.1.7 on 2025-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0016_fixed_expense_detail_emailnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_expense_detail',
            name='monthYear',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
