# Generated by Django 5.1.7 on 2025-07-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0017_fixed_expense_detail_monthyear'),
        ('stayease_supply', '0034_bed_data_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_category_detail',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='property_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_expenses', to='stayease_supply.property_data'),
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='resident',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
