# Generated by Django 5.1.7 on 2025-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0018_expense_category_detail_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_detail',
            name='property_instance',
        ),
    ]
