# Generated by Django 5.1.7 on 2025-07-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0019_remove_expense_detail_property_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_category_detail',
            name='gst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
