# Generated by Django 5.1.7 on 2025-07-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0020_expense_category_detail_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_category_detail',
            name='amountTransferredDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
