# Generated by Django 5.1.7 on 2025-08-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0021_expense_category_detail_amounttransferreddate'),
        ('stayease_supply', '0034_bed_data_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('utrNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('transferredDate', models.CharField(blank=True, max_length=100, null=True)),
                ('liability_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_bed', to='stayease_supply.bed_data')),
            ],
        ),
    ]
