# Generated by Django 5.1.7 on 2025-08-01 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0022_liability_detail'),
        ('stayease_supply', '0034_bed_data_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liability_detail',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='liability_detail',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability_detail',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liability_detail',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='liability_detail',
            index=models.Index(fields=['-last_activity'], name='stayease_ac_last_ac_617df1_idx'),
        ),
    ]
