# Generated by Django 5.1.7 on 2025-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0023_alter_liability_detail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability_detail',
            name='checkSendEmail',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
