# Generated by Django 5.1.7 on 2025-09-12 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0024_liability_detail_checksendemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Activity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Session')),
                ('session_duration', models.DurationField(blank=True, null=True, verbose_name='Session Duration')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Browser')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Django Session Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='stayease_ac_user_id_863180_idx'), models.Index(fields=['login_time'], name='stayease_ac_login_t_1074a9_idx'), models.Index(fields=['last_activity'], name='stayease_ac_last_ac_19a620_idx'), models.Index(fields=['is_active'], name='stayease_ac_is_acti_242a51_idx')],
            },
        ),
    ]
