# Generated by Django 5.1.7 on 2025-10-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0026_user_activity_data_user_login_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activity_data',
            name='dashboard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
