# Generated by Django 5.1.7 on 2025-10-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0027_user_activity_data_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity_data',
            name='dashboard',
        ),
    ]
