# Generated by Django 5.1.7 on 2025-10-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0028_remove_user_activity_data_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
