# Generated by Django 5.1.7 on 2025-12-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0029_delete_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_detail',
            name='email_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
