# Generated by Django 5.1.7 on 2025-12-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0030_expense_detail_email_thread_id'),
        ('stayease_sales', '0007_tenant_data_tenantstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liability_detail',
            name='liability_bed',
        ),
        migrations.AddField(
            model_name='liability_detail',
            name='liability_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liability_tenant', to='stayease_sales.tenant_data'),
        ),
    ]
