# Generated by Django 5.1.4 on 2026-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0031_remove_liability_detail_liability_bed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'sort_order'],
                'unique_together': {('group', 'value')},
            },
        ),
    ]
