# Generated by Django 5.1.7 on 2025-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContract_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(unique=True)),
                ('communityManager', models.CharField(max_length=100)),
                ('roomNo', models.CharField()),
                ('accommodationType', models.CharField()),
                ('monthlyFee', models.CharField()),
                ('stayDuration', models.CharField()),
                ('startDate', models.CharField()),
                ('endDate', models.CharField()),
                ('moveOutTime', models.CharField()),
                ('securityDeposit', models.CharField()),
                ('userFeeDueDate', models.CharField()),
                ('propertyAddress', models.CharField()),
                ('tenantContact', models.CharField()),
                ('status', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
