# Generated by Django 5.1.7 on 2025-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadDate', models.CharField()),
                ('leadSource', models.CharField()),
                ('name', models.CharField()),
                ('contact', models.CharField()),
                ('leadResult', models.CharField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='stayease_sa_last_ac_8fa811_idx')],
            },
        ),
    ]
