# Generated by Django 5.1.7 on 2025-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_detail',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leads_detail',
            name='notConvertedReason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
