# Generated by Django 5.1.7 on 2025-10-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0002_leads_detail_email_leads_detail_notconvertedreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Activity_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Login_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user_activity_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to='stayease_sales.user_activity_data')),
            ],
        ),
    ]
