# Generated by Django 5.1.7 on 2025-12-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0003_user_activity_data_user_login_data'),
        ('stayease_supply', '0036_user_activity_data_user_login_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyManager', models.CharField(blank=True, max_length=255, null=True)),
                ('salesManager', models.CharField(blank=True, max_length=255, null=True)),
                ('comfortClass', models.CharField(blank=True, max_length=255, null=True)),
                ('mealType', models.CharField(blank=True, max_length=255, null=True)),
                ('residentsName', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('permanentAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('kycType', models.CharField(blank=True, max_length=255, null=True)),
                ('aadharNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('aadharFrontCopy', models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/')),
                ('aadharBackCopy', models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/')),
                ('aadharStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('panNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('panFrontCopy', models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/')),
                ('panBackCopy', models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/')),
                ('panStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('checkIn', models.CharField(blank=True, max_length=255, null=True)),
                ('checkOut', models.CharField(blank=True, max_length=255, null=True)),
                ('totalDepositPaid', models.CharField(blank=True, max_length=255, null=True)),
                ('rentPerMonth', models.CharField(blank=True, max_length=255, null=True)),
                ('salesStatus', models.CharField(default='Pending')),
                ('moveInChecklistStatus', models.CharField(default='Pending')),
                ('moveInFeedbackStatus', models.CharField(default='Pending')),
                ('moveOutChecklistStatus', models.CharField(default='Pending')),
                ('moveOutFeedbackStatus', models.CharField(default='Pending')),
                ('rentStatus', models.CharField(default='Not Received')),
                ('transferType', models.CharField(blank=True, max_length=255, null=True)),
                ('utrNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('transferredDate', models.CharField(blank=True, max_length=255, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('bed_data_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_data_instance', to='stayease_supply.bed_data')),
            ],
        ),
    ]
