# Generated by Django 5.1.7 on 2025-12-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0004_tenant_data'),
        ('stayease_supply', '0036_user_activity_data_user_login_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_data',
            name='bed_data_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_data_instance', to='stayease_supply.bed_data'),
        ),
    ]
