# Generated by Django 5.1.7 on 2025-12-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0005_alter_tenant_data_bed_data_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant_data',
            name='salesStatus',
        ),
    ]
