# Generated by Django 5.1.7 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0006_remove_tenant_data_salesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_data',
            name='tenantStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
