# Generated by Django 5.1.7 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0006_remove_resident_data_salesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident_data',
            name='residentStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
