# Generated by Django 5.1.7 on 2025-12-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0007_tenant_data_tenantstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant_Rent_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentStatus', models.CharField(default='Not Received')),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('rent', models.CharField(blank=True, max_length=255, null=True)),
                ('delayCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('transferType', models.CharField(blank=True, max_length=255, null=True)),
                ('utrNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('transferredDate', models.CharField(blank=True, max_length=255, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('tenant_data_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_data_instance', to='stayease_sales.tenant_data')),
            ],
        ),
    ]
