# Generated by Django 5.1.4 on 2026-04-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0009_document_signingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_data',
            name='kycApprovalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='kycApprovalStatus',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='kycApprovedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='kycRejectionReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='pushNotificationToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='studentEmployeeIdCopy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant-documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='studentEmployeeIdNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='studentEmployeeIdType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant_data',
            name='tenantUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
