# Generated by Django 5.1.4 on 2026-04-24 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0011_rename_tenant_to_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_info', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('payu_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='stayease_sales.resident_rent_data')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='stayease_sales.resident_data')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['txnid'], name='stayease_sa_txnid_4d522a_idx')],
            },
        ),
    ]
