# Generated by Django 5.1.4 on 2026-04-24 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0012_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=64, unique=True)),
                ('auth_payu_id', models.CharField(blank=True, max_length=128, null=True)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('next_charge_date', models.DateField(blank=True, null=True)),
                ('last_charged_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_mandates', to='stayease_sales.resident_data')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['txnid'], name='stayease_sa_txnid_3e10c4_idx'), models.Index(fields=['status', 'next_charge_date'], name='stayease_sa_status_1f756b_idx')],
            },
        ),
    ]
