# Generated by Django 5.1.4 on 2026-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0014_paymentrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident_data',
            name='leaseAgreement',
            field=models.FileField(blank=True, null=True, upload_to='documents/lease-agreements/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resident_data',
            name='leaseUploadedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident_data',
            name='leaseUploadedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
