# Generated by Django 5.1.4 on 2026-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_sales', '0016_razorpay_gateway_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident_data',
            name='firstName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resident_data',
            name='lastName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
