# Generated by Django 5.1.4 on 2025-02-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normal_Enquirie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('comments', models.TextField()),
                ('submittedAt', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit_Enquirie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('property', models.CharField()),
                ('submittedAt', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Enquirie',
        ),
    ]
