# Generated by Django 5.1.7 on 2025-11-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stayease_supply', '0036_user_activity_data_user_login_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Activity_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoveInChecklistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveInRoom', models.CharField(blank=True, null=True)),
                ('moveInRoomComments', models.TextField(blank=True, null=True)),
                ('moveInWashroom', models.CharField(blank=True, null=True)),
                ('moveInWashroomComments', models.TextField(blank=True, null=True)),
                ('moveInKitchen', models.CharField(blank=True, null=True)),
                ('moveInKitchenComments', models.TextField(blank=True, null=True)),
                ('moveInLivingArea', models.CharField(blank=True, null=True)),
                ('moveInLivingAreaComments', models.TextField(blank=True, null=True)),
                ('moveInUtilities', models.CharField(blank=True, null=True)),
                ('moveInUtilitiesComments', models.TextField(blank=True, null=True)),
                ('moveInAccess', models.CharField(blank=True, null=True)),
                ('moveInAccessComments', models.TextField(blank=True, null=True)),
                ('moveInWelcomeKit', models.CharField(blank=True, null=True)),
                ('moveInWelcomeKitComments', models.TextField(blank=True, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('moveInChecklist_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveInChecklist_bed', to='stayease_supply.bed_data')),
            ],
        ),
        migrations.CreateModel(
            name='MoveInFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanlinessRoomWashroom', models.IntegerField(blank=True, null=True)),
                ('functionalityAppliancesUtilities', models.IntegerField(blank=True, null=True)),
                ('comfortSetupRoom', models.IntegerField(blank=True, null=True)),
                ('staffBehaviorCheckinExperience', models.IntegerField(blank=True, null=True)),
                ('overallImpressionStayease', models.IntegerField(blank=True, null=True)),
                ('overallComments', models.TextField(blank=True, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('moveInFeedback_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveInFeedback_bed', to='stayease_supply.bed_data')),
            ],
        ),
        migrations.CreateModel(
            name='MoveOutChecklistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveOutRoom', models.CharField(blank=True, null=True)),
                ('moveOutRoomComments', models.TextField(blank=True, null=True)),
                ('moveOutWashroom', models.CharField(blank=True, null=True)),
                ('moveOutWashroomComments', models.TextField(blank=True, null=True)),
                ('moveOutKitchen', models.CharField(blank=True, null=True)),
                ('moveOutKitchenComments', models.TextField(blank=True, null=True)),
                ('moveOutLivingArea', models.CharField(blank=True, null=True)),
                ('moveOutLivingAreaComments', models.TextField(blank=True, null=True)),
                ('moveOutAccess', models.CharField(blank=True, null=True)),
                ('moveOutAccessComments', models.TextField(blank=True, null=True)),
                ('moveOutDues', models.CharField(blank=True, null=True)),
                ('moveOutDuesComments', models.TextField(blank=True, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('moveOutChecklist_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveOutChecklist_bed', to='stayease_supply.bed_data')),
            ],
        ),
        migrations.CreateModel(
            name='MoveOutFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallStayExperience', models.IntegerField(blank=True, null=True)),
                ('cleanlinessPropertyStay', models.IntegerField(blank=True, null=True)),
                ('responsivenessPropertyTeam', models.IntegerField(blank=True, null=True)),
                ('commonareaKitchenExperience', models.IntegerField(blank=True, null=True)),
                ('recommendStayease', models.IntegerField(blank=True, null=True)),
                ('likeMostAboutStay', models.TextField(blank=True, null=True)),
                ('couldImprove', models.TextField(blank=True, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('moveOutFeedback_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveOutFeedback_bed', to='stayease_supply.bed_data')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyComplaintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDesc', models.TextField(blank=True, null=True)),
                ('preferredTime', models.CharField(blank=True, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('propertyComplaint_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyComplaint_bed', to='stayease_supply.bed_data')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('electricalElectronics', 'Electrical & Electronics'), ('plumbingBathroom', 'Plumbing & Bathroom'), ('furnituresFixtures', 'Furnitures & Fixtures'), ('kitchenEquipment', 'Kitchen Equipment'), ('internetConnectivity', 'Internet Connectivity'), ('others', 'Other Issues')], max_length=50)),
                ('items', models.TextField(blank=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('fromTime', models.CharField(blank=True, max_length=100)),
                ('toTime', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stayease_operations.propertycomplaintdetail')),
            ],
        ),
        migrations.CreateModel(
            name='User_Login_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user_activity_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to='stayease_operations.user_activity_data')),
            ],
        ),
    ]
