# Generated by Django 5.1.7 on 2025-11-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_accounts', '0029_delete_useractivity'),
        ('stayease_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcategory',
            name='complaint_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_vendor', to='stayease_accounts.vendor_detail'),
        ),
    ]
