# Generated by Django 5.1.7 on 2025-11-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0002_complaintcategory_complaint_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyComplaintDetail', to='stayease_operations.propertycomplaintdetail'),
        ),
        migrations.AlterField(
            model_name='complaintcategory',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Follow Up', 'Follow Up'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueResolved', models.TextField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('suggestions', models.CharField(blank=True, null=True)),
                ('submittedDateAndTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('complaint_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_feedback', to='stayease_operations.complaintcategory')),
            ],
        ),
    ]
