# Generated by Django 5.1.7 on 2025-11-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0003_alter_complaintcategory_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='stayease_operations.propertycomplaintdetail'),
        ),
    ]
