# Generated by Django 5.1.7 on 2025-11-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0004_alter_complaintcategory_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInAccess',
            new_name='moveInElectricalLighting',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInAccessComments',
            new_name='moveInElectricalLightingComments',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInKitchen',
            new_name='moveInFurnitureFixtures',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInKitchenComments',
            new_name='moveInFurnitureFixturesComments',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInLivingArea',
            new_name='moveInHousekeepingCleanliness',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInLivingAreaComments',
            new_name='moveInHousekeepingCleanlinessComments',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInRoom',
            new_name='moveInKitchenPlumbing',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInRoomComments',
            new_name='moveInKitchenPlumbingComments',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInUtilities',
            new_name='moveInPropertyCondition',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInUtilitiesComments',
            new_name='moveInPropertyConditionComments',
        ),
        migrations.RenameField(
            model_name='moveinchecklistdetail',
            old_name='moveInWashroomComments',
            new_name='moveInRemarks',
        ),
        migrations.RemoveField(
            model_name='moveinchecklistdetail',
            name='moveInWashroom',
        ),
        migrations.RemoveField(
            model_name='moveinchecklistdetail',
            name='moveInWelcomeKit',
        ),
        migrations.RemoveField(
            model_name='moveinchecklistdetail',
            name='moveInWelcomeKitComments',
        ),
    ]
