# Generated by Django 5.1.7 on 2025-11-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0005_rename_moveinaccess_moveinchecklistdetail_moveinelectricallighting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutAccess',
            new_name='moveOutElectricalLighting',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutAccessComments',
            new_name='moveOutElectricalLightingComments',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutDues',
            new_name='moveOutFurnitureFixtures',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutDuesComments',
            new_name='moveOutFurnitureFixturesComments',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutKitchen',
            new_name='moveOutHousekeepingCleanliness',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutKitchenComments',
            new_name='moveOutHousekeepingCleanlinessComments',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutLivingArea',
            new_name='moveOutKitchenPlumbing',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutLivingAreaComments',
            new_name='moveOutKitchenPlumbingComments',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutRoom',
            new_name='moveOutPropertyCondition',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutRoomComments',
            new_name='moveOutPropertyConditionComments',
        ),
        migrations.RenameField(
            model_name='moveoutchecklistdetail',
            old_name='moveOutWashroomComments',
            new_name='moveOutRemarks',
        ),
        migrations.RemoveField(
            model_name='moveoutchecklistdetail',
            name='moveOutWashroom',
        ),
    ]
