# Generated by Django 5.1.7 on 2025-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0006_rename_moveoutaccess_moveoutchecklistdetail_moveoutelectricallighting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=100, unique=True)),
                ('thread_id', models.CharField(max_length=255)),
                ('resident_email', models.EmailField(max_length=254)),
                ('resident_name', models.CharField(max_length=255)),
                ('category_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
