# Generated by Django 5.1.7 on 2025-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0007_emailthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycomplaintdetail',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycomplaintdetail',
            name='residentName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
