# Generated by Django 5.1.7 on 2025-12-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0009_alter_moveinchecklistdetail_moveinchecklist_bed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertycomplaintdetail',
            old_name='residentName',
            new_name='residentsName',
        ),
    ]
