# Generated by Django 5.1.4 on 2026-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_operations', '0010_rename_residentname_propertycomplaintdetail_residentsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycomplaintdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('electricalElectronics', 'Electrical & Electronics'), ('plumbingBathroom', 'Plumbing & Bathroom'), ('furnituresFixtures', 'Furniture & Fixtures'), ('kitchenEquipment', 'Kitchen Equipment'), ('internetConnectivity', 'Internet Connectivity'), ('others', 'Other Issues')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='propertycomplaintdetail',
            name='location',
            field=models.CharField(blank=True, choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('commonArea', 'Common Area'), ('balcony', 'Balcony'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='propertycomplaintdetail',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20),
        ),
    ]
