import React, { useRef, useCallback, useMemo, memo } from 'react'

// Table of contents data - defined outside component
const TABLE_OF_CONTENTS = [
    { id: 1, ref: 'sectionRef1', title: 'Acceptance of terms of service' },
    { id: 2, ref: 'sectionRef2', title: 'Eligibility' },
    { id: 3, ref: 'sectionRef3', title: 'Registration / sign up for service' },
    { id: 4, ref: 'sectionRef4', title: 'Content' },
    { id: 5, ref: 'sectionRef5', title: 'Conduct' },
    { id: 6, ref: 'sectionRef6', title: 'Third-Party Services' },
    { id: 7, ref: 'sectionRef7', title: 'Payments & Receipts' },
    { id: 8, ref: 'sectionRef8', title: 'Termination' },
    { id: 9, ref: 'sectionRef9', title: 'Governing Law, Jurisdiction and Dispute Resolution' }
]

// Memoized table of contents component
const TableOfContents = memo(({ scrollToSection }) => (
    <section className='relative hidden md:block'>
        <div className='sticky top-[10%] border border-white rounded-lg w-[25vw] px-5 py-8 shadow-lg'>
            <h4 className='text-xl md:text-2xl pb-[1.5rem] text-center font-semibold'>
                Table of Contents
            </h4>
            <ol className='space-y-2'>
                {TABLE_OF_CONTENTS.map((item) => (
                    <li key={item.id}>
                        <button
                            onClick={() => scrollToSection(item.ref)}
                            className='w-full text-left hover:text-[#eba312] transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:ring-offset-2 rounded px-2 py-1 text-sm lg:text-base'
                            aria-label={`Scroll to ${item.title}`}
                        >
                            <span className='underline'>{item.id}. {item.title}</span>
                        </button>
                    </li>
                ))}
            </ol>
        </div>
    </section>
))

TableOfContents.displayName = 'TableOfContents'

// Memoized section component
const TermsSection = memo(({ title, children, sectionRef }) => (
    <>
        <h4 ref={sectionRef} className='text-xl md:text-2xl pt-[3rem] pb-[1.5rem] font-semibold text-[#eba312]'>
            {title}
        </h4>
        <ul className='list-disc pl-5 space-y-4 text-gray-300 leading-relaxed'>
            {children}
        </ul>
    </>
))

TermsSection.displayName = 'TermsSection'

function TermsConditions() {
    // Create individual refs (these are stable across renders)
    const sectionRef1 = useRef(null)
    const sectionRef2 = useRef(null)
    const sectionRef3 = useRef(null)
    const sectionRef4 = useRef(null)
    const sectionRef5 = useRef(null)
    const sectionRef6 = useRef(null)
    const sectionRef7 = useRef(null)
    const sectionRef8 = useRef(null)
    const sectionRef9 = useRef(null)

    // Memoize the refs object to prevent recreation on each render
    const sectionRefs = useMemo(() => ({
        sectionRef1,
        sectionRef2,
        sectionRef3,
        sectionRef4,
        sectionRef5,
        sectionRef6,
        sectionRef7,
        sectionRef8,
        sectionRef9
    }), [
        sectionRef1, sectionRef2, sectionRef3, sectionRef4, sectionRef5,
        sectionRef6, sectionRef7, sectionRef8, sectionRef9
    ])

    // Memoized scroll function - depends on stable sectionRefs object
    const scrollToSection = useCallback((refKey) => {
        sectionRefs[refKey]?.current?.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
        })
    }, [sectionRefs])

    return (
        <div className='pt-[8rem] md:pt-[10rem] pb-[1rem] md:pb-[2rem] px-[1rem] md:px-[5rem] lg:px-[8rem]'>
            {/* Header */}
            <div className='text-center mb-5'>
                <h1 className="text-2xl md:text-4xl font-semibold my-3 md:my-5 text-[#eba312]">
                    Terms & Conditions
                </h1>
            </div>

            {/* Main Content with Table of Contents */}
            <div className='flex flex-col md:flex-row md:space-x-20 mt-[2rem] md:mt-[5rem] pb-[2rem] lg:pb-[5rem]'>
                {/* Table of Contents - Desktop */}
                <TableOfContents scrollToSection={scrollToSection} />

                {/* Terms Content */}
                <section className='md:w-[70%]'>
                    {/* Introduction */}
                    <div className='space-y-4 text-gray-300 leading-relaxed'>
                        <p>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        <p>
                            This document is published in accordance with the provisions of Section 3(1) of Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of through the domain and subdomains of Stayease. located at www.mystayease.com and/or through "Stayease" mobile applications (collectively referred to herein as the "Platform").
                        </p>
                        <p>
                            The Platform is owned by Estancia Ease Pvt Ltd (under the brand name "Stayease") Stayease operates, controls and manages the Services (as defined below) provided by it from its corporate office at No. 216,215, 3rd Cross, Off Neeladri Road, Electronic City Phase 1, Bengaluru 560100 (hereinafter referred to as "Stayease").
                        </p>
                    </div>

                    {/* Section 1 */}
                    <TermsSection title="Acceptance of terms of service" sectionRef={sectionRefs.sectionRef1}>
                        <li>By registering for and/or using the Services in any manner, including but not limited to visiting or browsing the Site, user agrees to these Terms of Service and all other operating rules, policies, and procedures that may be published from time to time on the Site by the Company, each of which is incorporated by reference and each of which may be updated from time to time without notice to the user.</li>
                        <li>Certain of the Services may be subject to additional terms and conditions specified by the Company from time to time; use of such Services by the user is subject to those additional terms and conditions, which are incorporated into these Terms of Service by this reference.</li>
                        <li>These Terms of Service apply to all users of the Services, including, without limitation, users who are contributors of content, information, and other materials or services, registered or otherwise.</li>
                    </TermsSection>

                    {/* Section 2 */}
                    <TermsSection title="Eligibility" sectionRef={sectionRefs.sectionRef2}>
                        <li>You represent and warrant that you are at least 18 years of age. If you are under age 18, you may not, under any circumstances or for any reason, use the Services. We may, in our sole discretion, refuse to offer the Services to any person or entity and change the eligibility criteria at any time. You are solely responsible for ensuring that you are in compliance with these Terms of Service and all laws, rules, and regulations applicable to you, and the right to access the Services is revoked where you are not in compliance with these Terms of Service, where use of the Services is prohibited, or to the extent the offering, sale or provision of the Services conflicts with any applicable law, rule or regulation. Further, the Services are offered only for your use, and not for the use or benefit of any third party.</li>
                    </TermsSection>

                    {/* Section 3 */}
                    <TermsSection title="Registration / sign up for service" sectionRef={sectionRefs.sectionRef3}>
                        <li>As part of the Services, the user may be required to register for a user account with Stayease through an application provided by Stayease (an "Account"). The user must provide accurate and complete information and keep his/her Account information updated. The user shall not: (i) select or use as a username a name of another person with the intent to impersonate that person; (ii) use as a username a name subject to any rights of a person other than the user without appropriate authorization; or (iii) use, as a username, a name that is otherwise offensive, vulgar or obscene.</li>
                        <li>User's Account information may include information that is personal to the user, such as his/her name, email address and phone number (collectively called "personal details"). user shall only provide his/her own personal details. user shall not provide personal details of any third person. user must update his/her Account information to reflect any change to his/her personal details. If at any time any portion of Account information of the user is inaccurate or incomplete, or if user otherwise violate these Terms of Service, Company may in its sole discretion and without advance notice choose to suspend or terminate user's subscriptions / services, and Account or all three.</li>
                        <li>The user is solely responsible for the activity that occurs on user's Account, and for keeping user's Account password secure and/or not share user login OTP to anyone. user shall never use another person's user account or registration information for the Services without permission. user must notify the Company immediately of any change in his/her eligibility to use the Services, breach of security or unauthorised use of user/s Account. user should never publish, distribute or post login information for his/her Account.</li>
                        <li>By creating an Account, user agrees to accept and receive communications from the Company as part of Company's provision of the Services, including via email, text message and calls, and/or push notifications to the registered mobile/telephone number and/or email address user provided to the Company.</li>
                        <li>By creating an Account, user agrees and give consent for Company to reach the user through Whatsapp Business Profile and receive communications from the Company. user can delete his/her account once user's subscription ends with the Company, via emailing the Company at users@mystayease.com, Company will delete user's account in 60 working days post receiving the request and there are no active subscription contracts with the Company. Once the account is deleted user shall not be able to access previously subscribed contracts, and invoices, and the user will be treated as a new user.</li>
                    </TermsSection>

                    {/* Section 4 */}
                    <TermsSection title="Content" sectionRef={sectionRefs.sectionRef4}>
                        <li><span className='font-semibold text-white'>Definition:</span> For purposes of these Terms of Service, the term "Content" includes, without limitation, information, data, text, photographs, videos, audio clips, written posts and comments, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible on or through the Services.</li>
                        <li><span className='font-semibold text-white'>Content - user acknowledges</span> that all Content accessed by the user using the Services is at user's own risk and user will be solely responsible for any damage or loss to the user or any other party resulting therefrom. Company does not guarantee that any Content the user accesses on or through the Services is or will continue to be accurate.</li>
                        <li><span className='font-semibold text-white'>Notices and Restrictions:</span> The Services may contain Content specifically provided by the Company, its partners or its users and such Content is protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws. user shall abide by and maintain all copyright notices, information, and restrictions contained in any Content accessed through the Services.</li>
                        <li><span className='font-semibold text-white'>Use License:</span> Subject to these Terms of Service, Company grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable user to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content for purposes other than using the Services is expressly prohibited without prior written permission from the Company. user shall not sell, user, rent, or otherwise use or exploit any Content for commercial use or in any way that violates any third party right. This user does not grant user any ownership rights in the Content.</li>
                        <li><span className='font-semibold text-white'>Availability of Content:</span> Company does not guarantee that any Content will be made available on the Site or through the Services. Company reserves the right to, but do not have any obligation to, (i) remove, edit or modify any Content in Company's sole discretion, at any time, without notice to user and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if Company are concerned that user may have violated these Terms of Service), or for no reason at all and (ii) to remove or block any Content from the Services.</li>
                    </TermsSection>

                    {/* Section 5 */}
                    <TermsSection title="Conduct" sectionRef={sectionRefs.sectionRef5}>
                        <li>It is agreed by the license holder/user that he/she shall not use the services for any purpose that is prohibited by these Terms of Service. The license holder/user shall be responsible for all of his/her activity in connection with the Services. user shall not (and shall not permit any third party to) either (a) take any action or (b) upload, download, post, submit or otherwise distribute or facilitate distribution of any Content on or through the Services, that:</li>
                        <li>The user undertakes to not infringes any patent, trademark, trade secret, copyright, right of publicity or other right of any other person or entity or violates any law or contractual duty;</li>
                        <li>User shall not disseminate any information which he/she knows is false, misleading, untruthful or inaccurate; is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another's privacy, tortious, obscene, vulgar, pornographic, offensive, profane, contains or depicts nudity, contains or depicts sexual activity, or is otherwise inappropriate as determined by the Company in its sole discretion;</li>
                        <li>User shall not conduct in any manner which constitutes unauthorized or unsolicited advertising, junk or spamming emails/text;</li>
                        <li>User shall not disseminate any thing which contains software viruses or any other computer codes, files, or programs that are designed or intended to disrupt, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of the Company or of any third party;</li>
                        <li>User shall not impersonate any person or entity, including any of Company's employees or representatives; or includes anyone's identification documents or sensitive financial information.</li>
                        <li>User shall not: (i) take any action that imposes or may impose (as determined by the Company in its sole discretion) an unreasonable or disproportionately large load on the Company (or Company's third party providers') infrastructure; (ii) interfere or attempt to interfere with the proper working of the Services or any activities conducted on the Services; (iii) bypass, circumvent or attempt to bypass or circumvent any measures Company may use to prevent or restrict access to the Services (or other accounts, computer systems or networks connected to the Services); (iv) run any form of auto-responder or "spam" on the Services; (v) use manual or automated software, devices, or other processes to "crawl" or "spider" any page of the Site; (vi) harvest or scrape any Content from the Services; or (vii) otherwise take any action in violation of Company's guidelines and policies.</li>
                        <li>User shall not (directly or indirectly): (i) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Services (including without limitation any application), except to the limited extent applicable laws specifically prohibit such restriction, (ii) modify, translate, or otherwise create derivative works of any part of the services, or (iii) copy, rent, lease, distribute, or otherwise transfer any of the rights that user receives hereunder. user shall abide by all applicable local, state, national and international laws and regulations.</li>
                    </TermsSection>

                    {/* Section 6 */}
                    <TermsSection title="Third-Party Services" sectionRef={sectionRefs.sectionRef6}>
                        <li>All the services, which are not directly and exclusively provided by the Company are third party services. Unless the service provided is classified as being provided by the Company, it is deemed to be a third party service. The Company, for the sake of convenience of the user, may provide links/information of third party websites, services or resources available on the Internet. All transactions of the user with the third party resources on the Internet, shall be at the own risk of the user and no liability/claim shall be made to the Company for any deficiency, loss or harm caused to the user due to the use of such third party services.</li>
                        <li>The user acknowledges that these third party resources are not under the control of the Company, and the License acknowledges that Company is not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such websites or resources. The inclusion of any such link on the website of the Company does not imply its endorsement or any association between the Company and any third party operators.</li>
                        <li>Including but not limited to the services mentioned below, the following shall be considered to be third party services and Rectification of any fault in Third Party Services such as Wifi, Lift, Electricity, Water Supply, Water Tanker, DG Fuel, Inverter, repair or replacement of electrical appliances - TV, AC, Induction stove, Microwave oven, Geyser, Kitchen inventories etc, shall be carried out as per the TAT policy of Stayease. However, no request for waiver in the rent will be entertained for the non-availability of any of such services.</li>
                    </TermsSection>

                    {/* Section 7 */}
                    <TermsSection title="Payments & Receipts" sectionRef={sectionRefs.sectionRef7}>
                        <li><span className='font-semibold text-white'>Rental Receipts:</span> The Company shall send the rental receipts to the registered email in the beginning of every month and the rental is to be paid by 5th of the same month to avoid late fee charges, and the same is to be paid through a designated account number which is unique to each user and/or pay through debit /or credit card, The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Gateway. user agrees to make payment using that selected Payment Method. Company reserve the right to correct any errors or mistakes that the Payment Gateway makes even if it has already requested or received payment, The Monthly Rental does not include taxes. a 12% GST will be applied over and above the monthly rental. Kindly be advised that NEFT/UPI transactions are exempt from payment gateway charges if done via virtual account number/id provided. However, if the payment is processed through a payment gateway, the applicable charges will be the responsibility of the sublessee.</li>
                        <li><span className='font-semibold text-white'>Deposits:</span> The user needs to pay three months of security deposit, (i) The user is required to pay a part of the deposit referred as booking/ or token amount at the time of booking, (ii) The Security deposit to be paid will be mentioned in the subscription agreement and the same can be paid through Online and/or cheque, (iii) In the case where the user chooses to make an internal transfer from one property to another or upgrade his/her current occupancy type /booking, the difference in the amount of security deposit will be expected to be paid by the user before him/her making the actual transfer or upgrade. In case the new rent is lower than the previous one, the difference in security deposit is adjusted against the following month's rent.</li>
                        <li><span className='font-semibold text-white'>Refunds:</span> The booking amount paid is non-refundable and all refunds shall be as per the refund policy of the Company.</li>
                        <li><span className='font-semibold text-white'>Refunds on Move-out:</span> The security deposit shall be refunded, post a fixed deduction of Property Management Fees and any physical damage to the assets at the premises by conducting a move-out audit as per policies set out in the subscription agreement, within 15 bank working days from the day of move-out, (i) In case, the user terminates the subscription during the lock-in period, Stayease shall be entitled to deduct one month's rent which shall be deducted from the security deposit at the time of moving out. Hereinafter referred to as "Contract breakage charges", (ii) If the user terminates the subscription after the expiry of the lock-in period without prior intimation of 30 days to Stayease., rent of one month shall be levied on the user which shall be deducted from the deposit at the time of moving out. Hereinafter referred to as "Notice Period charges", (iii) Any unpaid rent, utility payments, late fee payment will be deducted from the security deposit at the time of moveout.</li>
                        <li><span className='font-semibold text-white'>Contract Extension:</span> The Contract Extensions are accepted and confirmed through the Stayease Mobile Application or Forms shared by time and again, the confirmation is valid if confirmed over an email/telephonic and /or whatsapp communication from the registered mobile / email address registered with the Company.</li>
                        <li><span className='font-semibold text-white'>Move-out:</span> The user must inform Stayease at least 30 days before they intend to move out through Company's application and/or via email to users@mystayease.com, (i) The user will have to pay the entire month's rent if move-out date is after the 3rd of the successive month. The Deposit will be refunded to the user in 30 bank working days from the End Date after deducting unpaid charges/damages, if any. The refund will be done only through an online transfer that is submitted and/or through payout links through Company's payment gateway partner.</li>
                        <li><span className='font-semibold text-white'>Mode of Refund:</span> The security deposit will be refunded via online transfer to the registered bank account of the user as per Company's records. and/or through payment links generated through our payment gateway partner</li>
                        <li>To ensure the security of your transactions, please make all payments via the designated virtual account number visible in the app. Alternatively, you can use payment links verified with the Estancia Ease Private Limited Badge.</li>
                        <li>Stayease will never collect payments through on-ground staff, including property managers, housekeeping staff, or cluster managers.</li>
                        <li>Payments are never accepted via QR codes or personal accounts. If you encounter any suspicious requests, please report them immediately to our Customer Success Team. Stay vigilant and secure with Stayease!</li>
                        <li>Please note that a processing fee may be applied to payments made through the payment gateway.</li>
                    </TermsSection>

                    {/* Section 8 */}
                    <TermsSection title="Termination" sectionRef={sectionRefs.sectionRef8}>
                        <li>In the event of default by the user on the payment of Licence fee, Utility charges, and other charges as mentioned in the agreement, for a period more than 12 days from the time invoice has been raised, the company shall be at liberty entitled to forfeit the entire security deposit and use reasonable force to remove the user from the premises.</li>
                        <li>In the following events, the Company shall terminate the subscription immediately with a deduction of two-month Rent from the security deposit.</li>
                        <li>Involved in any illegal activity within or outside the Premises and the user and/or the guest of the user is detained for the same.</li>
                        <li>Involved in drug abuse.</li>
                        <li>Misbehaviour with the other user of the property and Company by the user and/or his/her guest. The Company shall be at liberty to initiate action against the user suo-motu or on the basis of a complaint by other users.</li>
                        <li>Any other situation at the discretion of Stayease, which would compromise the peace and tranquillity at the premises.</li>
                    </TermsSection>

                    {/* Section 9 */}
                    <TermsSection title="Governing Law, Jurisdiction and Dispute Resolution" sectionRef={sectionRefs.sectionRef9}>
                        <li>The subscription agreement shall be governed by and enforced as per the Laws in India and for the purpose of enforcement; the place of jurisdiction will be the city in which the Premises are located.</li>
                        <li>In the event of any dispute arising out of or in connection with the agreement, the Parties shall, at first instance, attempt to amicably resolve the same through settlement discussions (recorded by way of email or telephonic conversations).</li>
                        <li>If Parties are unable to resolve their disputes within thirty (30)days of written intimation, the disputes will be referred to arbitration under the Arbitration and Conciliation Act, 1996 and its amendments from time to time. The arbitration will be conducted by a sole arbitrator appointed by mutual consent within 7 (seven) days of the receipt of the notice to arbitrate. All disputes shall be submitted for arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996. The seat of Arbitration shall be Bangalore.</li>
                        <li>If Parties are unable to mutually agree, Company shall have the right to approach the appropriate court for appointment of the sole arbitrator. The process of arbitration shall be decided by the arbitrator in accordance with the provisions of the Arbitration Act. The cost of arbitration (including all legal costs) will be borne by the losing Party. Till the continuation of the proceedings and passing of the award, all the Parties will bear their own share of cost and can recover the same, once the award is passed, from the losing Party.</li>
                    </TermsSection>
                </section>
            </div>
        </div>
    )
}

export default memo(TermsConditions)