# Generated by Django 5.1.7 on 2025-07-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stayease_supply', '0017_owner_data_accountstatus_owner_data_paymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyDeductionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('monthly_values', models.JSONField(default=list)),
                ('cumulative_total', models.FloatField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stayease_supply.owner_data')),
            ],
            options={
                'unique_together': {('owner', 'year')},
            },
        ),
    ]
